# Логин от ВКонтакте
vk-login: "ВашЛогинОтВК"
# Пароль от ВКонтакте
vk-password: "ВашПарольОтВК"
# Нежелательно ставить значение менее, чем 20 секунд, так как у ВК есть защита от флуда запросами
timeout: 5