# Логин от ВКонтакте
vk-login: "79264342011"
# Пароль от ВКонтакте
vk-password: "Egor112112112vk"
# Нежелательно ставить значение менее, чем 20 секунд, так как у ВК есть защита от флуда запросами
timeout: 5